### ISSUE TITLE
HTTP code 400 unexpected: Duplicate mount point

### ISSUE THREAD

**Issue by hanfreakingsolo** [MichelFR/MqDockerUp#154]
I triggered an update for my plex container through home assistant. The image pulls fine and I see the container get renamed, but after a minute I see this error:
```
25.10.2023 14:26:54 [info]      Image pulled successfully
Container died: plex (4f0979a2e61aa4c572d2f54112fcf5f441724291fac4897c99c3d98f4f475773)
25.10.2023 14:27:29 [error]     MqDockerUp stopped due to an error
25.10.2023 14:27:29 [error]     object
25.10.2023 14:27:29 [error]     Error: (HTTP code 400) unexpected - Duplicate mount point: /PlexMedia 
    at /app/node_modules/docker-modem/lib/modem.js:343:17
    at getCause (/app/node_modules/docker-modem/lib/modem.js:373:7)
    at Modem.buildPayload (/app/node_modules/docker-modem/lib/modem.js:342:5)
    at IncomingMessage.<anonymous> (/app/node_modules/docker-modem/lib/modem.js:310:16)
    at IncomingMessage.emit (node:events:526:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21)
```

**Comment by MichelFR** [comment]
It Seems like you mounted PlexMedia twice.
Creating a Volume for /PlexMedia would probably fix that issue.

Closing for now

**Comment by hanfreakingsolo** [comment]
> Error: (HTTP code 400) unexpected - Duplicate mount point

I have created a volume, docker compose up works without issue. Here is my compose file:

```
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        limits:
          cpus: "0.75"
    environment:
      - PUID=568
      - PGID=568
      - TZ=America/Toronto
      - VERSION=docker
      - PLEX_CLAIM="redacted"
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,video,utility      
    volumes:
      - ./plex/config:/config
      - ./plex/transcode:/transcode
      - PlexMedia:/PlexMedia
    restart: unless-stopped
```
```
volumes:
  downloads:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.11,nfsvers=4"
      device: ":/mnt/truenasZ2/downloads/qbittorent"
  PlexMedia:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.0.11,nfsvers=4"
      device: ":/mnt/truenasZ2/PlexMedia"
```
