### ISSUE TITLE
Cannot get the Docker up and running

### ISSUE THREAD

**Issue by matteo-martinelli** [MichelFR/MqDockerUp#156]
Hello!

I am trying the get the container running but I can't get it work. I changed the configuration file and the docker-compose file a hundred times, and I strongly believe I made some mistakes there.

The log Docker returns is the following:

```
Starting MqDockerUp V1.3.3 ... 
TypeError: Cannot read properties of undefined (reading 'dockerhub')
    at Function.getConfig (/app/src/services/ConfigService.ts:47:107)
    at Object.<anonymous> (/app/src/services/HomeassistantService.ts:6:30)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module.m._compile (/app/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .ts] (/app/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:121:18)
TypeError: Cannot read properties of undefined (reading 'dockerhub')
    at Function.getConfig (/app/src/services/ConfigService.ts:47:107)
    at Object.<anonymous> (/app/src/index.ts:12:30)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module.m._compile (/app/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .ts] (/app/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at phase4 (/app/node_modules/ts-node/src/bin.ts:649:14)
/app/src/index.ts:13
const client = mqtt.connect(config.mqtt.connectionUri, {
                                   ^
TypeError: Cannot read properties of undefined (reading 'mqtt')
    at Object.<anonymous> (/app/src/index.ts:13:36)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module.m._compile (/app/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .ts] (/app/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at phase4 (/app/node_modules/ts-node/src/bin.ts:649:14)
    at bootstrap (/app/node_modules/ts-node/src/bin.ts:95:10)
```

My docker-compose: 

```
version: '3.9'

services:
  mqdockerup:
    image: micrib/mqdockerup:v1.3.3
    container_name: Mq-Docker-Up
    restart: always
     #environment:
     #  MAIN_INTERVAL: "30s"
     #  MQTT_CONNECTIONURI: "mqtt://192.168.1.51:1883"
     #  MQTT_USERNAME: mqtt-user
     #  MQTT_PASSWORD: mqtt-pw
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./mqdockerup-container/app/data:/app/data
      - ./mqdockerup-container/config.yaml:/app/config.yaml
    networks:
      - mq-docker-up-bridge
    secrets: 
      - mqtt-user
      - mqtt-pw

secrets:
  mqtt-user:
    file: ./secrets/mqtt-usr.txt
  mqtt-pw:
    file: ./secrets/mqtt-pw.txt

networks:
  mq-docker-up-bridge: 
    external: true
```

My config file: 

```
main:
  interval: "5m"

mqtt:
  connectionUri: "mqtt://192.168.1.51:1883"
  topic: "homeassistant/system/mqdockerup"
  clientId: "mqdockerup"
  username: "my_mqtt_user"
  password: "my_mqtt_password"
  connectTimeout: 60
  protocolVersion: 5
```

Can you please help me?
