### ISSUE TITLE
Implement network configuration on container update

### ISSUE THREAD

**Issue by schumi2004** [MichelFR/MqDockerUp#191]
This is the perfect addon to manage my containers but today i noticed after updating a few that it ignores my networks configuration assigned to containers.

Many of my containers have a static IP configured like this but it gets ignored when you update them via HA/MQTT, it assigns a completly different IP from the same subnet to my containers.
Any idea why and how this happens and can it be fixed?

```
    networks:
      ipvlan_custom:
        ipv4_address: 10.0.0.181

networks:
  ipvlan_custom:
    name: ipvlan_custom
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1
```
