### ISSUE TITLE
mqdockerup container stop

### ISSUE THREAD

**Issue by maurilloh** [MichelFR/MqDockerUp#21]
Hi MichelFR,

This is my docker compose file:

version: "3.9"
services:
  mqdockerup:
    image: micrib/mqdockerup
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - MQTT_CONNECTIONURI=mqtt://192.168.0.30:1883
      - MAIN_INTERVAL=5m
      - MQTT_CLIENTID=mqdockerup
      - MQTT_CONNECTTIMEOUT=60
      - MQTT_HA_DISCOVERY=true
      - MQTT_PASSWORD=mypassword
      - MQTT_QOS=2
      - MQTT_RETAIN=false
      - MQTT_TOPIC=mqdockerup
      - MQTT_USERNAME=myusername
      - MQTT_PROTOCOLVERSION=5
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

The container starts but it show only:

 mqdockerup@0.12.2 start
> node dist/src/index.js
📦 MqDockerUp version 0.12.2

if i cancel the env MQTT_PROTOCOLVERSION the container show this and then stops:

> mqdockerup@0.12.2 start
> node dist/src/index.js
📦 MqDockerUp version 0.12.2
🚀 Connected to MQTT broker
🔍 Checking for updates...
🔍 HomeAssistant discovery activated
🔁 Checking for image updates every 5m
🔍 Finished checking for image updates
🕒 Next check in 5 minutes
💥 MqDockerUp stopped due to an error at 3/2/2023, 5:12:56 PM

what am i wrong? I use the env because i don't know where the config.yaml is stored :)

**Comment by MichelFR** [comment]
First of all, thank you for using MqDockerUp and reporting your issue.

Currently, some of the configs don't work as expected, and they don't have any functionality. I apologize for any inconvenience this may have caused you.

Please try using the following YAML configuration (adapted to your needs) and see if it resolves your issue:

```yaml
version: '3.9'

services:
  mqdockerup:
    image: micrib/mqdockerup:latest
    restart: always
    environment:
      MQTT_HA_DISCOVERY: "true"
      MQTT_CONNECTIONURI: "mqtt://127.0.0.1:1883"
      MQTT_USERNAME: "ha"
      MAIN_INTERVAL: "1m"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: MqDockerUp
```

I'll implement a logging functionality soon to help with debugging issues like this.

If possible, please let me know which container images you are using and their tags, as that may also help with troubleshooting.

Thank you again for using MqDockerUp and for bringing this issue to my attention.

**Comment by maurilloh** [comment]
Hi MichelFR,

Thank you to you for your work :)

With your YAML configuration (i've added MQTT_PASSWORD env) i have this error:

 mqdockerup@0.12.4 start
> node dist/src/index.js
/app/node_modules/mqtt/lib/connect/index.js:72
      throw new Error('Missing protocol')
      ^
Error: Missing protocol
    at Object.connect (/app/node_modules/mqtt/lib/connect/index.js:72:13)
    at Object.<anonymous> (/app/dist/src/index.js:23:31)
    at Module._compile (node:internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
    at Module.load (node:internal/modules/cjs/loader:1133:32)
    at Module._load (node:internal/modules/cjs/loader:972:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:83:12)
    at node:internal/main/run_main_module:23:47
Node.js v19.7.0

I've tried to change also the ip but same error.

**Comment by MichelFR** [comment]
Hmm by the error it seems you maybe have forgotten to add mqtt:// to the connection URI.

When you log outputs: "Connected to MQTT broker" then you can be sure its not a problem with mqtt.

In your first comment it seems to have problem getting the running docker containers

**Comment by maurilloh** [comment]
Hi,

yes you are right. I've changed the ip address and now I've this:

> mqdockerup@0.12.4 start
> node dist/src/index.js
📦 MqDockerUp version 0.12.4
🚀 Connected to MQTT broker
🔍 Checking for updates...
🔍 HomeAssistant discovery activated
🔁 Checking for image updates every 1m
🔍 Finished checking for image updates
🕒 Next check in 1 minute
💥 MqDockerUp stopped due to an error at 3/3/2023, 4:38:17 PM

**Comment by MichelFR** [comment]
Based on my observation, the system appears to encounter difficulties retrieving container information. I suggest waiting for my upcoming implementation of an improved logging logic that can aid in identifying the root cause of the issue. Should you encounter any further logs or errors, please provide them as they can be helpful in resolving this matter.

**Comment by MichelFR** [comment]
I just released a new version of MqDockerUp, you should now get some more information when something goes wrong.

**Comment by maurilloh** [comment]
this is what i have now:

     
> mqdockerup@0.12.5 start
> node dist/src/index.js
  __  __       ____             _             _   _       
 |  \/  | __ _|  _ \  ___   ___| | _____ _ __| | | |_ __  
 | |\/| |/ _` | | | |/ _ \ / __| |/ / _ \ '__| | | | '_ \ 
 | |  | | (_| | |_| | (_) | (__|   <  __/ |  | |_| | |_) |
 |_|  |_|\__, |____/ \___/ \___|_|\_\___|_|   \___/| .__/ 
            |_|                                    |_|    
Starting MqDockerUp V0.12.5 ... 
03.03.2023 20:41:03 [error] 	MqDockerUp stopped due to an error
03.03.2023 20:41:03 [error] 	Connection refused: Not authorized
{
  "code": 135
}

**Comment by MichelFR** [comment]
This error occures because it cannot connect to MQTT please check the connectionUri again and that MQTT is running and reachable

**Comment by maurilloh** [comment]
i don't know, the mqtt integration in HA has the same address and username/password and it works, i've tried to change the protocol version in the integratin and if i put 5 it does't work anymore. it's set to 3.1.1
i've tried also to put mqtt_protocolversion to 3.1.1 or 5 on the container but without success

**Comment by MichelFR** [comment]
It seems like you previously had already successfully connected before since you got the entity in HomeAssistant. MQTT-Protocol should be backwards compatible so that your problem lays somewhere else.

**Comment by MichelFR** [comment]
Hi @maurilloh I’m closing this issue as I haven’t heard anything further from you. I hope your problem has been resolved. If not, please feel free to reopen this issue and provide more details. 

Thank you for your feedback!

**Comment by frittes** [comment]
Hi,

I have also problems connecting to the broker.

> 1678633356: New connection from 172.28.0.2:59724 on port 1883.
1678633356: Client <unknown> closed its connection.

This is my docker-compose.yml

```
version: '3.9'

services:
  mqdockerup:
    image: micrib/mqdockerup:latest
    restart: always
    environment:
      MAIN_INTERVAL: "1m"
      MQTT_CONNECTIONURI: "mqtt://192.168.44.220:1883"
      MQTT_USERNAME: "mqdockerup"
      MQTT_PASSWORD: "test123"
      MQTT_TOPIC: "mqdockerup"
      MQTT_CLIENTID: "mqdockerup"
      MQTT_PROTOCOLVERSION: 5 
      MQTT_CONNECTTIMEOUT: 60
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: mqdockerup 
```

Tried everything: Use an easier password, set the container to host network mode, tried other protocol versions...

Broker runs on the same machine.

Any hints to get it running?

**Comment by MichelFR** [comment]
> Hi,
> 
> I have also problems connecting to the broker.
> 
> > 1678633356: New connection from 172.28.0.2:59724 on port 1883.
> > 1678633356: Client  closed its connection.
> 
> This is my docker-compose.yml
> 
> ```
> version: '3.9'
> 
> services:
>   mqdockerup:
>     image: micrib/mqdockerup:latest
>     restart: always
>     environment:
>       MAIN_INTERVAL: "1m"
>       MQTT_CONNECTIONURI: "mqtt://192.168.44.220:1883"
>       MQTT_USERNAME: "mqdockerup"
>       MQTT_PASSWORD: "test123"
>       MQTT_TOPIC: "mqdockerup"
>       MQTT_CLIENTID: "mqdockerup"
>       MQTT_PROTOCOLVERSION: 5 
>       MQTT_CONNECTTIMEOUT: 60
>     volumes:
>       - /var/run/docker.sock:/var/run/docker.sock
>     container_name: mqdockerup 
> ```
> 
> Tried everything: Use an easier password, set the container to host network mode, tried other protocol versions...
> 
> Broker runs on the same machine.
> 
> Any hints to get it running?

What are your logs from the running docker container?

if you re using MQTT Protocol v3 try changing the value in the docker-compose to:

3.1.1

**Comment by PeteSSMMSS** [comment]
Hey I have the same problem: 
If I don´t add MQTT_PROTOCOLVERSION: 3 or 3.1.1 or 5 in docker-compose.yaml I get the error 

```
Starting MqDockerUp V0.14.4 ... 
18.03.2023 09:31:59 [error] 	MqDockerUp stopped due to an error
18.03.2023 09:31:59 [error] 	object
18.03.2023 09:31:59 [error] 	Error: Connection refused: Not authorized
    at MqttClient._handleConnack (/app/node_modules/mqtt/lib/client.js:1388:17)
    at MqttClient._handlePacket (/app/node_modules/mqtt/lib/client.js:549:12)
    at work (/app/node_modules/mqtt/lib/client.js:438:12)
    at Writable.writable._write (/app/node_modules/mqtt/lib/client.js:452:5)
    at doWrite (/app/node_modules/readable-stream/lib/_stream_writable.js:389:139)
    at writeOrBuffer (/app/node_modules/readable-stream/lib/_stream_writable.js:380:5)
    at Writable.write (/app/node_modules/readable-stream/lib/_stream_writable.js:301:11)
    at Socket.ondata (node:internal/streams/readable:766:22)
    at Socket.emit (node:events:512:28)
    at addChunk (node:internal/streams/readable:324:12)
```

If I add MQTT_PROTOCOLVERSION: (tried all different numbers) I get just this:

```
> mqdockerup@0.14.4 start
> node dist/src/index.js
  __  __       ____             _             _   _       
 |  \/  | __ _|  _ \  ___   ___| | _____ _ __| | | |_ __  
 | |\/| |/ _` | | | |/ _ \ / __| |/ / _ \ '__| | | | '_ \ 
 | |  | | (_| | |_| | (_) | (__|   <  __/ |  | |_| | |_) |
 |_|  |_|\__, |____/ \___/ \___|_|\_\___|_|   \___/| .__/ 
            |_|                                    |_|    
Starting MqDockerUp V0.14.4 ... 
```
without any more details. My Mosquitto broker in  Home Assistant is definitely working I checked also the credentials twice. In the logs I get a lot of this:

```
2023-03-18 10:34:23: New connection from 192.168.178.123:39960 on port 1883.
2023-03-18 10:34:23: Client <unknown> closed its connection.
2023-03-18 10:34:24: New connection from 192.168.178.123:39962 on port 1883.
2023-03-18 10:34:24: Client <unknown> closed its connection.
2023-03-18 10:34:25: New connection from 192.168.178.123:39964 on port 1883.
2023-03-18 10:34:25: Client <unknown> closed its connection.
2023-03-18 10:34:26: New connection from 192.168.178.123:39966 on port 1883.
2023-03-18 10:34:26: Client <unknown> closed its connection.
2023-03-18 10:34:27: New connection from 192.168.178.123:39968 on port 1883.
2023-03-18 10:34:27: Client <unknown> closed its connection.
2023-03-18 10:34:28: New connection from 192.168.178.123:39970 on port 1883.
2023-03-18 10:34:29: Client <unknown> closed its connection.
2023-03-18 10:34:30: New connection from 192.168.178.123:39976 on port 1883.
2023-03-18 10:34:30: Client <unknown> closed its connection.
```

But none of them shows up in Home Assistant...

My docker-compose.yaml:

```
version: '3.9'

services:
  mqdockerup:
    image: micrib/mqdockerup:latest
    restart: always
    environment:
      MQTT_CONNECTIONURI: "mqtt://192.168.178.XX:1883"
      MQTT_USERNAME: "XXX"
      MQTT_PASSWORD: "XXX"
      MAIN_INTERVAL: "5m"
      MQTT_PROTOCOLVERSION: 5 
      MQTT_CLIENTID: "mqdockerup"
      MQTT_TOPIC: "mqdockerup"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    container_name: MqDockerUp
```
