### ISSUE TITLE
Multiple instances of MqDockerUp conflict with each other

### ISSUE THREAD

**Issue by chriswood1001** [MichelFR/MqDockerUp#261]
I have several docker instances on different computers, each running MqDockerUp. I'm able to successfully differentiate between the updates by having unique mqtt topics and mqtt clientID's.

However, the home assistant mqtt discovery data conflicts when the same container exists on both docker instances.

My config for docker server one:
```
main:
  interval: "5m"

mqtt:
  connectionUri: "mqtt://192.168.10.100:1883"
  topic: "mqdockerup/server_one"
  clientId: "mqdockerup_server_one"
  username: "homeassistant"
  password: "password"
  connectTimeout: 60
  protocolVersion: 5

accessTokens:
  dockerhub:
  github:
```

And, my config for docker server two:
```
main:
  interval: "5m"

mqtt:
  connectionUri: "mqtt://192.168.10.100:1883"
  topic: "mqdockerup/server_two"
  clientId: "mqdockerup_server_two"
  username: "homeassistant"
  password: "password"
  connectTimeout: 60
  protocolVersion: 5

accessTokens:
  dockerhub:
  github:

```

Using MQTT Explorer I see the status reported as expected, without conflict.
```
/mqdockerup/server_one/ <my containers>
/mqdockerup/server_two/ <my containers>
```

However, the Home Assistant discover data conflicts as both servers try to write to:
```
/homeassistant/sensor/micrib_mqdockerup_latest/
```

Is there a way to address this?
