### ISSUE TITLE
V1.18.0 not updating anymore, also tag gives 404

### ISSUE THREAD

**Issue by lucize** [MichelFR/MqDockerUp#445]
Seems that I can't update anything anymore, also there are lots of 404 if you tag images with anything, seems to always search for latest tag

```
12.03.2025 22:54:34 [info] 
  __  __       ____             _             _   _       
 |  \/  | __ _|  _ \  ___   ___| | _____ _ __| | | |_ __  
 | |\/| |/ _` | | | |/ _ \ / __| |/ / _ \ '__| | | | '_ \ 
 | |  | | (_| | |_| | (_) | (__|   <  __/ |  | |_| | |_) |
 |_|  |_|\__, |____/ \___/ \___|_|\_\___|_|   \___/| .__/ 
            |_|                                    |_|    
Starting MqDockerUp V1.18.0 ... 
12.03.2025 22:54:35 [info] Connected to the database.
12.03.2025 22:54:35 [info] MQTT client successfully connected
12.03.2025 22:54:35 [info] Checking for removed containers...
12.03.2025 22:54:35 [info] Database initialized successfully
12.03.2025 22:54:35 [info] Checking for containers...
12.03.2025 22:54:35 [info] Finished checking for containers
12.03.2025 22:54:35 [info] Next check in 5 minutes
12.03.2025 22:54:35 [info] Checking for image updates...
..
12.03.2025 22:54:39 [info] Image ghcr.io/analogj/scrutiny:master-omnibus is up-to-date
12.03.2025 22:54:39 [error] Error getting image info: (HTTP code 404) no such image - No such image: ghcr.io/analogj/scrutiny:latest 
12.03.2025 22:54:39 [info] Repository not found: ghcr.io/analogj/scrutiny
12.03.2025 22:54:39 [warn] Could not find source repository for ghcr.io/analogj/scrutiny

```
snip

```
services:
  scrutiny:
    container_name: scrutiny
    image: ghcr.io/analogj/scrutiny:master-omnibus
    cap_add:
      - SYS_RAWIO
    ports:
      - "8083:8080" # webapp
      - "8087:8086" # influxDB admin
```
