### ISSUE TITLE
Problem starting the container

### ISSUE THREAD

**Issue by SpaceFrags** [MichelFR/MqDockerUp#449]
Hello,

I get this error message in the logs:

```
17.03.2025 17:34:32 [info] 
  __  __       ____             _             _   _       
 |  \/  | __ _|  _ \  ___   ___| | _____ _ __| | | |_ __  
 | |\/| |/ _` | | | |/ _ \ / __| |/ / _ \ '__| | | | '_ \ 
 | |  | | (_| | |_| | (_) | (__|   <  __/ |  | |_| | |_) |
 |_|  |_|\__, |____/ \___/ \___|_|\_\___|_|   \___/| .__/ 
            |_|                                    |_|    
Starting MqDockerUp V1.18.1 ... 
17.03.2025 17:34:40 [error] Cannot read properties of null (reading 'main')
17.03.2025 17:34:41 [error] Cannot read properties of null (reading 'main')
17.03.2025 17:34:45 [error] Cannot read properties of null (reading 'main')
/app/src/services/HomeassistantService.ts:11
const haLegacy = ConfigService.autoParseEnvVariable(config.mqtt?.haLegacy)
                                                           ^
TypeError: Cannot read properties of undefined (reading 'mqtt')
    at Object.<anonymous> (/app/src/services/HomeassistantService.ts:11:60)
    at Module._compile (node:internal/modules/cjs/loader:1364:14)
    at Module.m._compile (/app/node_modules/ts-node/src/index.ts:1618:23)
    at Module._extensions..js (node:internal/modules/cjs/loader:1422:10)
    at Object.require.extensions.<computed> [as .ts] (/app/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1203:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1019:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/app/src/services/DockerService.ts:7:1)
```

This is my docker compose file:

```
  mqdockerup:
    image: micrib/mqdockerup:latest
    container_name: mqdockerup
    hostname: mqdockerup
    restart: always
    environment:
      MAIN_CONTAINERCHECKINTERVAL: "5m"
      MAIN_UPDATECHECKINTERVAL: ""
      MAIN_PREFIX: ""
      MQTT_CONNECTIONURI: "mqtt://127.0.0.1:1883"
      MQTT_TOPIC: "mqdockerup"
      MQTT_DISCOVERYPREFIX: "homeassistant"
      MQTT_CLIENTID: "mqdockerup"
      MQTT_USERNAME: "my_username"
      MQTT_PASSWORD: "my_pass"
      MQTT_CONNECTTIMEOUT: 60
      MQTT_PROTOCOLVERSION: 5
      ACCESSTOKENS_DOCKERHUB: "my_token_dockerhub"
      ACCESSTOKENS_GITHUB: "my_token_Github"
      IGNORE_CONTAINERS: ""
      IGNORE_UPDATES: ""
      LOGS_LEVEL: "info"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${USERDIR}/docker/mqdockerup/data:/app/data/ 
      - ${USERDIR}/docker/mqdockerup/config.yaml:/app/config.yaml
```

What am I doing wrong? 

I noticed that my config.yaml is empty when the container is running, I had to create it with "nano" before running the Docker Compose :)
